### PR TITLE
Fixed missing BlankProject

### PR DESCRIPTION
**Pull request by homapf**
#### Changes

- Removed creation and deletion of BlankProject on Mac runners

Deleting the BlankProject on cleanup creates the following issue when calling the action multiple times in a row:
```bash
Couldn't set project path to: 

Aborting batchmode due to failure:
Couldn't set project path to: 

[Package Manager] Server::Kill -- Server was shutdown
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: There was an error while trying to activate the Unity license.
Error: Build failed with exit code 1
```

There is no need to create the BlankProject as it already exists in the action.

#### Successful Workflow Run Link

This only affects self-hosted mac runners. Cannot share a workflow run here unfortunately.

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make a PR
      in the [documentation repo](https://github.com/game-ci/documentation))
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by GabLeRoux — APPROVED** [review]
This looks good to me, I'm wondering if the same problem happens on the test runner action.

**Comment by homapf** [comment]
Any blocker to merge @GabLeRoux ?

I'd gladly look at the test runner action if I have some time.

**Comment by webbertakken** [comment]
The code that's being removed here doesn't fail by itself. 

- `mkdir -p "$ACTIVATE_LICENSE_PATH"` has the `-p` flag that makes sure it doesn't fail if the folder already exists.
- `rm -r "$ACTIVATE_LICENSE_PATH"` will never fail because the folder is guaranteed to exist.

The change you're proposing doesn't actually fix any error as far as I can see. What am I missing?

**Comment by webbertakken** [comment]
cc: @GabLeRoux

**Comment by GabLeRoux** [comment]
I agree; removing those two lines doesn’t seem to address what’s mentioned in the description. If this issue persists, let’s open a discussion to confirm the right approach.

It’s possible we might be overlooking something, but I don’t currently see how these changes resolve what’s outlined. Let us know if we can help. :)

**Pull request closed without merging**
