### PR TITLE
implement alternative to allow pull with github token 

### PR DESCRIPTION
**Pull request by mad01**
#### Changes
implementation allowing you to pass github token as suggested in #161 to handle windows/linux/macos and github action envs. 

```yaml
      - name: preload-unity-project
        uses: mad01/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: iOS
          unityVersion: 2018.4.26f1
          buildMethod: X
          gitPrivateToken: ${{ secrets.GIT_PRIVATE_TOKEN }}
```

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
Interesting approach! And thank you for your PR.

Please allow us some time to discuss if we want to support this kind of behaviour and whether it would be in this shape.

**Comment by mad01** [comment]
Sure. i just needed something that worked better in out setup where we have local settings for the packages where they are accessed using https while in the CI setup we needed to use tokens

**Comment by russovincenzo** [comment]
@mad01 I try to use your action but I got this error while the container try to pull repo:

```
com.art.gradientspacemodule: Cannot checkout repository [https://github.com/<hidden>/GradientSpaceModule.git]:
      Error when executing git command. Downloading GradientSpaceModule~/Assets/StreamingAssets/DeleteFromReleaseBuild/Meshes/TestMesh/BowtieConnectedTriangles.obj (279 B)
      Error downloading object: GradientSpaceModule~/Assets/StreamingAssets/DeleteFromReleaseBuild/Meshes/TestMesh/BowtieConnectedTriangles.obj (dbe3949): Smudge error: Error downloading GradientSpaceModule~/Assets/StreamingAssets/DeleteFromReleaseBuild/Meshes/TestMesh/BowtieConnectedTriangles.obj (dbe39496dec7a4a405d4d5b77b637e473c41b092a4db19aadecbf567bf6b433e): batch response: Bad credentials

      Errors logged to /github/workspace/Library/PackageCache/.tmp129BA7LkSpHqv0j/clone/.git/lfs/objects/logs/20210906T143617.094425013.log
      Use `git lfs logs last` to view the log.
      error: external filter 'git-lfs filter-process' failed
      fatal: GradientSpaceModule~/Assets/StreamingAssets/DeleteFromReleaseBuild/Meshes/TestMesh/BowtieConnectedTriangles.obj: smudge filter lfs failed
```

Any Idea?

I try to pull the repo with personal access token on my local machine without any issue

**Comment by mad01** [comment]
I have no idea. i am using it atm. here is a example of how it looks for me. A note is that i have only tested this change with unity 2018
```
name: Unity
on: [push]
jobs:

  build-unity:
    runs-on: [self-hosted, Linux, X64, studio]
    strategy:
      max-parallel: 1
    steps:
      # Checkout
      - name: Check repository
        uses: actions/checkout@v2
        with:
          lfs: false
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: recursive

      - name: build-unity-project
        uses: mad01/unity-builder@7f1bc277f7beae52cec88a9cc191a2461a1339aa
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: iOS
          unityVersion: 2018.4.26f1
          buildMethod: "***.Build.Core.Editor.BatchInterface.PreloadBuildAndExport"
          gitPrivateToken: ${{ secrets.GIT_PRIVATE_TOKEN }}
          allowDirtyBuild: true
          customParameters: |
            -platform iOS
            -defineSymbols 'BUILD_VERBOSE
            -buildNumberOffset 0
            -bundleId com.***.***
            -configurationId com.***.***
            -username='${{ secrets.USERNAME }}' -password='${{ secrets.PASSWORD }}'
```

**Comment by davidmfinol** [comment]
@mad01 Can you pull from the main branch and rebuild?
We've already merged the corresponding change into the test runner, and I think it would be good to have this change for builder.

**Comment by davidmfinol** [comment]
I went ahead and merged with https://github.com/game-ci/unity-builder/pull/296

**Pull request closed without merging**
