### PR TITLE
Removed checks for old unity versions

### PR DESCRIPTION
**Pull request by EliasVal**
#### Changes

Changed referenced EOL versions in tests to LTS and Current versions (2018.x-2020.x -> 2021.x-2023.x)

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make
            a PR in the [documentation repo](https://github.com/game-ci/documentation))
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by EliasVal** [comment]
@webbertakken As promised :)
Let me know if any further changes are needed

**Comment by webbertakken** [comment]
Looks good to me. 

Note that this is just the checks to make sure `unity-builder` works as expected. We'll still need to do the same for `test-runner` and other actions that use the images. https://github.com/game-ci/docker/issues/220 is for changing the workflow to no longer even publish these images in the first place.

**Comment by EliasVal** [comment]
> We'll still need to do the same for `test-runner` and other actions that use the images. 
@webbertakken So just change any reference to a version earlier than 2021.x to use 2022 LTS?

**Comment by webbertakken** [comment]
> > We'll still need to do the same for `test-runner` and other actions that use the images.
> 
> @webbertakken So just change any reference to a version earlier than 2021.x to use 2022 LTS?

Not sure I understand the question to be honest. Also we're supporting all non-EOL versions, not just LTS.

So basically what we have to do is stop publishing EOL images in the `game-ci/docker` repository (which is done in `game-ci/versioning-backend` I believe. And the usages of it, like here in builder like you did.

**Comment by webbertakken** [comment]
Which is to say you marked this PR as "resolves" the docker issue, but that is to stop publication of EOL images, not just usage. So we need to unlink that resolves-link.

**Comment by EliasVal** [comment]
> Which is to say you marked this PR as "resolves" the docker issue, but that is to stop publication of EOL images, not just usage. So we need to unlink that resolves-link.

Sure, on it!

> Not sure I understand the question to be honest. Also we're supporting all non-EOL versions, not just LTS.
> 
> So basically what we have to do is stop publishing EOL images in the game-ci/docker repository (which is done in game-ci/versioning-backend I believe. And the usages of it, like here in builder like you did.


What I meant here is, to change every field that references the EOL versions to 2022.x (2021.x is EOL in April so 2022.x gives us more headroom)

i.e `game-ci/unity-test-runner/src/model/docker.test.ts`, `const image = '....2019.2.11f1...'`, to `const image = '...2022.3.7f1....'`

**Comment by webbertakken** [comment]
I see. Yes sounds good to me!

**Review by webbertakken — APPROVED** [review]

**Pull request merged**
