### PR TITLE
Fix defaults

### PR DESCRIPTION
**Pull request by AndrewKahr**
#### Changes

- ...

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by davidmfinol** [comment]
Is there a reason to completely remove the `default` line for `androidExportType`, instead of doing `default: ''`?

**Comment by AndrewKahr** [comment]
I'm not sure exactly how inputs works. I'm relying on it not being defined to know whether to prioritize over the app bundle parameter. If '' counts as undefined then it can be added as default.

**Comment by AndrewKahr** [comment]
@davidmfinol Is it preferred to have an empty string default? I can see about changing the logic to support that.

**Comment by davidmfinol** [comment]
I think it would be better to have to the empty string default, so that it is consistent with how we are defining all the other inputs.

**Review by davidmfinol — APPROVED** [review]

**Review by davidmfinol — APPROVED** [review]

**Pull request merged**
