### PR TITLE
Misc QOL Updates and bug fixes

### PR DESCRIPTION
**Pull request by AndrewKahr**
#### Changes

- Add `cacheUnityInstallationOnMac` parameter to cache Unity Hub/Editor on MacOS runners. This can significantly reduce build times that need a macos runner
- Add `unityHubVersionOnMac` parameter to pin Unity Hub version on MacOS runners
- Support other target platforms on MacOS runners
- Enable log output streaming to console rather than outputting the whole log in one go on MacOS runners
- Improve build failure detection for all platforms. Builds with errors should now fail the workflow properly
- Updated PR Template Links
- Add `androidExportType` parameter to enable exporting as `androidPackage (apk)`, `androidAppBundle(aab)`, or `androidStudioProject (Android Project)`
- Enforce minimum node version to >=16
- Added `yarn-audit-fix` to dev dependencies
- Updated vulnerable packages
- Add deprecation warning to favor using `androidExportType` over `buildAndroidAppBundle`
- Add `androidSymbolType` parameter to allow building public or debugging symbols for android
- Change windows build script to use `$LastExitCode` and not `$?` to fix exit code not being captured correctly
- Update Default Build Script to support the new parameters
- Update Default Build Script to work on Unity 2018 versions by removing out variable declarations
- Update tests to cover the latest version of each minor Unity version
- Add retry logic to windows test builds as there seem to be more activation errors than other platforms

This should handle #411, #356, #325, PR#471, PR#443, and PR#418.

This is supported by game-ci/documentation#362

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by AndrewKahr** [comment]
Seems the way I am doing symbol generation doesn't work on older Unity versions, will make a fix

**Comment by AndrewKahr** [comment]
The android failing build in 2022.2 is due to a Unity bug so that one is expected to fail

**Review by davidmfinol — APPROVED** [review]

**Comment by davidmfinol** [comment]
Any idea why builds for 2019.2.11f1 are showing as "Expected" and not "Successful"?

**Comment by AndrewKahr** [comment]
I'm not sure. Either the workflow needs to be approved to run or it's because I updated the PR workflow to run more Unity versions and those got superseded. I'm guessing the latter though.

**Comment by AndrewKahr** [comment]
@davidmfinol It might be this: https://github.com/orgs/community/discussions/26698

Are you able to look at branch protection rules?

**Comment by davidmfinol** [comment]
@AndrewKahr Yep that was it.

**Pull request merged**
