### PR TITLE
Fixed bug with additional 'c:' prefix for --workDir

### PR DESCRIPTION
**Pull request by Mannilie**
#### Changes

- Removed the `'c:'` prefix from the `--workDir` path for Windows hosts.

#### Related Issues

- https://github.com/game-ci/unity-builder/issues/643

#### Successful Workflow Run Link

PRs don't have access to secrets so you will need to provide a link to a successful run of the workflows from your own
repo.

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [X] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make a PR
      in the [documentation repo](https://github.com/game-ci/documentation))
- [X] Readme (updated or not needed)
- [X] Tests (added, updated or not needed)

## Summary by CodeRabbit

- **New Features**
	- Improved compatibility of the Docker command for cross-platform usage by removing the hardcoded `C:` prefix from the workspace path.

- **Bug Fixes**
	- Enhanced flexibility in workspace path configuration, allowing for better adaptability across different environments.

### CODE REVIEW

**Comment by AndrewKahr** [comment]
What seems a little odd about this is in v2, it was hardcoded to c:/github/workspace which nobody seemed to have any issues with. We currently have a Windows 11 runner building successfully on V4 without touching the workdir variable, so maybe there's another variable at play?

Here's the v3 commit with the changes for reference: https://github.com/game-ci/unity-builder/commit/3032a4ab97a9bb3fe204eeecd61b5abcc14885d3

**Comment by Mannilie** [comment]
Hey @AndrewKahr, I agree. 
It does seem weird but as I understand, the path should be relative as opposed to absolute for the `--workDir` argument. 

Unless I'm missing something, even in the action items you've written, I believe we're on the same page that it should definitely be omitted from the command.
image

**Comment by AndrewKahr** [comment]
It was instructed to leave out the drive letter because the variable was shared between Linux and Windows, so the Windows function would prepend the `c:` portion while the Linux one doesn't prepend the `c:`. So at the action level, it is still technically absolute pathing with an assumption of a c drive in the container for Windows containers. And at the docker level, it is supposed to be absolute.

This sounds like you could be hitting a path conversion error based on the shell that's being used: https://github.com/docker/cli/issues/2204
https://stackoverflow.com/questions/40213524/using-absolute-path-with-docker-run-command-not-working

This makes the fix tricky since people with self-hosted runners may be using different ENV vars/shell types on their runners.

**Comment by Mannilie** [comment]
@AndrewKahr thanks for pointing me in the right direction with this!

Happy to report that I managed to find the fix to the issue. If anyone runs into this issue, the solution is quite simple. 
I noticed that on Dockers Desktop there's an option to utilize both `Linux Containers` and `Windows Containers`. 

By default, my machine was set to Linux Containers which is **_not_** which causes the following error:
image

When you switch it to `Windows Containers`:
image

The docker service should spin up without any errors:
image


Thanks again for your help @AndrewKahr , can happily close this ticket! 😄

**Comment by webbertakken** [comment]
@AndrewKahr do we have a suggested approach for a PR, or recommended values for those variables on self-hosted? Perhaps we can get a quick win by streamlining this.

Related:

- https://discord.com/channels/710946343828455455/1287679642110791731
- https://github.com/game-ci/unity-builder/issues/663
- https://github.com/game-ci/unity-builder/issues/643

**Pull request closed without merging**
