### PR TITLE
BREAKING (potentially) - Bump docker version (Ubuntu 22.04 LTS)

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- This PR will change the rolling tag from v1 to v2. That means that it will always use the latest v2 docker image. This is a potentially breaking change, however we do not expect most people to experience problems with this upgrade.
- Fixes a couple of vulnerabilities and a compilation error
- Pin Volta versions (so that Volta users will automatically use the right versions of node and yarn)

#### Checklist

- [x] Read the contribution [guide](https://github.com/game-ci/unity-builder/blob/main/CONTRIBUTING.md) and accept the
      [code](https://github.com/game-ci/unity-builder/blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Docs (If new inputs or outputs have been added or changes to behavior that should be documented. Please make
            a PR in the [documentation repo](https://github.com/game-ci/documentation))
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by EliasVal** [comment]
Small Question 😅 
Why are Unity versions that have reached EOL are still having tests ran with? 2018.x, 2019.x and 2020.x have reached their EOL's a long while back and I think that support should be dropped for versions that Unity doesn't support themselves

**Comment by webbertakken** [comment]
> Small Question 😅 Why are Unity versions that have reached EOL are still having tests ran with? 2018.x, 2019.x and 2020.x have reached their EOL's a long while back and I think that support should be dropped for versions that Unity doesn't support themselves

It's a great question. I think we probably should stop pushing images for them. The reason we haven't is that some of the rationale is brought up by a very small amount of people. And we miss things. You bringing it up is really much appreciated.

I've created an issue for it https://github.com/game-ci/docker/issues/220

**Comment by webbertakken** [comment]
Docker @ https://github.com/game-ci/docker/pull/216
Docs @ https://github.com/game-ci/documentation/pull/407

**Comment by EliasVal** [comment]
> It's a great question. I think we probably should stop pushing images for them. The reason we haven't is that some of the rationale is brought up by a very small amount of people. And we miss things. You bringing it up is really much appreciated.
> 
> I've created an issue for it https://github.com/game-ci/docker/issues/220

Of course! I'd like to help with development and I've yet to sit down on my PC to actually make PRs so until now I've only helped with already existing issues and PRs :D
The first issue I'm gonna tackle is probably this one :)

**Review by AndrewKahr — APPROVED** [review]
LGTM!

**Comment by sbergen** [comment]
In case you are interested in an example of how this can break things, I'm sharing this just FYI:

I'm using a [two year old custom image](https://github.com/sbergen/Responsible/blob/main/docfx/Dockerfile) to generate docfx documentation, and the [build fails when updating from v2 to v3](https://github.com/sbergen/Responsible/actions/runs/5986328388/job/16239340970?pr=212).  The error is a bit jarring, but I assume just updating the custom image should help. I'm not sure when I'll get to that, but I'll probably ask in Discord if I face any issues.

**Comment by webbertakken** [comment]
Thanks for sharing that input @sbergen!

**Review by GabLeRoux — COMMENTED** [review]
nice work 👍

**Pull request merged**
